controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
kernel:
    resource: App\Kernel
    type: attribute
register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_generate_pdf:
    path: '/generate-pdf'
    controller: 'App\Controller\BackOfficeUserController::generatePdf'

oauth_check:
    path: /oauth/check/{service}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController